#!/bin/bash

# ------------------------------------------------------------------------------
# Check if debug tracing was requested. If yes then 'set -x'.

if [[ ${1,,} = "debug" ]] ; then
  echo "Debug tracing has been enabled."
  set -x
  fi

# ------------------------------------------------------------------------------
# Program Identification.

export __NAME="hp3k_sim"
export __TITLE="HP3000 MPE V/E Simulator Utility"
export __VERSION="A.00.00" # v.uu.ff
  # v  = version (A-Z).
  # uu = update (00-99). Reset to 00 on change of 'version'.
  # ff = fix (00-99). Reset to 00 on change of 'update'.
export __AUTHOR="Robert W.Mills"
export __COPYRIGHT="Copyright © ${__AUTHOR} <rwmills.uk@gmail.com>, 2025-2025."
export __IMAGE="${HOME}/bin/data/hp3k_sim.jpg"
export __LICENSE="GPL3"

# ------------------------------------------------------------------------------
# Program Return Status.
#
# Status   Description
# ------  ----------------------------------------------------------------------
#    0    Completed without errors.
#    1    INIFILE does not exist or is not readable.
#    2    Unable to find yad.
#    3    Unable to find enscript.
#    4    Unable to find ps2pdf (part of GhostScript).
#    5    The Host Port required by the Convertor is currently in use.
#    6    The Simulator has failed to start.
#    7    The Convertor has failed to start.

# ------------------------------------------------------------------------------
# Declare where the Windows format INI file that holds the default configuration
# data for this program is located.

export INIFILE="${HOME}/bin/data/hp3k_sim.ini"

# = Functions ==================================================================

# ------------------------------------------------------------------------------
# Returns the value for a key and [section] from the file pointed to by INIFILE.
#
# Syntax: Value=$(IniValue Key Section)
#
# Parameters:
#   Key             A string (quoted if it contains spaces) or a string
#                   variable holding the name of the key to be searched for. 
#   Section         A string (quoted if it contains spaces) or a string
#                   variable holding the name of the section to be searched
#                   for. A leading [ and trailing ] must be included.
#
# Return:
#   Value           The value held for the searched for Section & Key.

IniValue() {
  local strKey="$1"
  local strSection="$2"
  local strRecord=""
  local strCurrKey=""
  local strValue=""

  while read strRecord ; do # Loop until EOF INIFILE.

    while : ; do # Loop until section found.
      # Strip leading and trailing spaces.
      strRecord="${strRecord#"${strRecord%%[![:space:]]*}"}"
      strRecord="${strRecord%"${strRecord##*[![:space:]]}"}"
      if [[ "${strRecord}" == "${strSection}" ]] ; then # Found section.
        break
        fi
      read strRecord
      done

    while : ; do # Loop until key found.
      read strRecord ; status=$?
      if [[ ${status} == "1" ]] ; then # Found EOF INIFILE.
        break
        fi
      # Strip leading and trailing spaces.
      strRecord="${strRecord#"${strRecord%%[![:space:]]*}"}"
      strRecord="${strRecord%"${strRecord##*[![:space:]]}"}"
      strCurrKey=${strRecord%=*}
      # Strip leading and trailing spaces.
      strCurrKey="${strCurrKey#"${strCurrKey%%[![:space:]]*}"}"
      strCurrKey="${strCurrKey%"${strCurrKey##*[![:space:]]}"}"
      if [[ "${strCurrKey}" == "${strKey}" ]] ; then # Found key.
        strValue=${strRecord#*=}
        # Strip leading and trailing spaces.
        strValue="${strValue#"${strValue%%[![:space:]]*}"}"
        strValue="${strValue%"${strValue##*[![:space:]]}"}"
        echo -n "$strValue"
        return
        fi
      done

    done < ${INIFILE}

  }

# ------------------------------------------------------------------------------
# Display the LinePrinter to PDF Convertor Configuration Help Dialog.

convertor_help() {

  cmd=( yad \
    --center \
    --fixed \
    --align=left \
    --text-width=40 \
    --borders=20 \
    --window-icon="${__IMAGE}" \
    --title="${__TITLE}" \
    --borders=20 \
    --text="\
'Line Printer to PDF Convertor':

This dialog displays the Convertor settings along with the settings for the
Terminal Window that the Convertor will run in.

Use either the -/+ buttons to decrease/increase the displayed values OR
highlight the value to be changed and enter a new value.

PDF Output Media is currently for information only. Its use will be expanded in
a later version.

Lines per Bar lets you change the height of the alternating bars in the PDF
file. Use a value of 0 (zero) to disable the bars.

Bar Colour lets you change the colour of the alternating bars in the PDF file.
Click on the ▼ symbol and select the required colour from the list displayed.

PDF Directory lets you change the directory where the PDF files will be stored.
Click on the ▼ symbol and select the required directory from the list displayed.
If the directory you want is not in this list then click on 'Other..' and a
standard 'Select' dialog will be displayed. Select the folder to use in the
normal manner.

PDF Font and Size is currently for information only. Its use will be expanded in
a later version.

System Name and Printer Name if entered will only appear in the Status Messages
output by the Convertor. Their use will be expanded in a later version.

You can adjust the Width (columns), the Height (rows), the 'location' of the
Terminal Window and the Text Size. Use the -/+ buttons to decrease/increase the
displayed values OR highlight the value to be changed and enter a new value.

Text Size lets you adjust the size of the text within the Terminal Window.
Use a value of 1.0 to set the text to its Full Size, 0.8 to reduce its size by
20% and 1.2 to increase its size by 20%.

Click the [Continue] button when you are ready to continue.

Click the [Cancel] button if you wish to terminate the program." \
    --button="Close"
    )

  "${cmd[@]}"

  }

export -f convertor_help

# ------------------------------------------------------------------------------
# Display the LinePrinter to PDF Convertor Configuration Dialog.

convertor() {

  # Display dialog box with default values.

  yad_cmd=$( yad \
    --form \
    --center \
    --align=left \
    --no-escape \
    --borders=20 \
    --window-icon="${__IMAGE}" \
    --title="${__TITLE}" \
    --text="Make your required changes and click [Continue] or [Cancel] to Exit:" \
    --focus-field=1 \
    --num-output \
    --field="\nLine Printer to PDF Convertor\n:LBL" "" \
    --field="    Host IP Address" "${HOST_IP}" \
    --field="    Host TCP Port:NUM" "${HOST_PORT}" \
    --field="    PDF Output Media!See Help for more details.:RO" "${PDF_MEDIA}" \
    --field="    Lines per Bar!See Help for more details.:NUM" "${BAR_LINES}"\
    --field="    Bar Colour!Sets the colour of the alternating bars in the PDF file.:CB" "${BAR_COLOURS}" \
    --field="    PDF Directory!See Help for more details.:DIR" "${PDF_DIRECTORY}" \
    --field="    PDF Font and Size!See Help for more details.:RO" "${PDF_FONT}" \
    --field="    System Name (optional)!See Help for more details." "${SYSTEM_ID}"\
    --field="    Printer Name (optional)!See Help for more details." "${PRINTER_ID}"\
    --field="\nWindow Configuration\n:LBL" "" \
    --field="    Width!Sets the width in columns.:NUM" "${CONV_WIDTH}" \
    --field="    Height!Sets the height in rows.:NUM" "${CONV_HEIGHT}" \
    --field="    X Cordinate!Number of pixels between the left-hand side of the Screen and the left-hand side of the Window.:NUM" "${CONV_XCOORD}" \
    --field="    Y Cordinate!Number of pixels between the top of the Screen and the top of the Window.:NUM" "${CONV_YCOORD}" \
    --field="    Text Size!Set the size of the Text (1.0 = Full Size, 0.5 = 50% (Half Size), 2.0 = 200% (Double Size)):NUM" "${CONV_TEXT}!!0.1!1" \
    --field="\n:LBL" "" \
    --button="Help!!Displays the Help dialog.":"bash -c convertor_help" \
    --button="Cancel":1 \
    --button="Continue":0
    )

  status=$?

  if [[ ${status} -eq 1 ]]; then # Cancel button pressed.
    echo "** Program has been cancelled by the user."
    exit 0
    fi

  # Load returned values into global variables.

  #NOT_USED=`echo ${yad_cmd} | awk --field-separator='|' '{print $1}'`
  HOST_IP=`echo ${yad_cmd} | awk --field-separator='|' '{print $2}'`
  HOST_PORT=`echo ${yad_cmd} | awk --field-separator='|' '{print $3}'`
  PDF_MEDIA=`echo ${yad_cmd} | awk --field-separator='|' '{print $4}'`
  BAR_LINES=`echo ${yad_cmd} | awk --field-separator='|' '{print $5}'`
  BAR_COLOUR=`echo ${yad_cmd} | awk --field-separator='|' '{print $6}'`
  PDF_DIRECTORY=`echo ${yad_cmd} | awk --field-separator='|' '{print $7}'`
  PDF_FONT=`echo ${yad_cmd} | awk --field-separator='|' '{print $8}'`
  SYSTEM_ID=`echo ${yad_cmd} | awk --field-separator='|' '{print $9}'`
  PRINTER_ID=`echo ${yad_cmd} | awk --field-separator='|' '{print $10}'`
  #NOT_USED=`echo ${yad_cmd} | awk --field-separator='|' '{print $11}'`
  CONV_WIDTH=`echo ${yad_cmd} | awk --field-separator='|' '{print $12}'`
  CONV_HEIGHT=`echo ${yad_cmd} | awk --field-separator='|' '{print $13}'`
  CONV_XCOORD=`echo ${yad_cmd} | awk --field-separator='|' '{print $14}'`
  CONV_YCOORD=`echo ${yad_cmd} | awk --field-separator='|' '{print $15}'`
  CONV_TEXT=`echo ${yad_cmd} | awk --field-separator='|' '{print $16}'`

  }

export -f convertor

# ------------------------------------------------------------------------------
# Display the Simulator Selection and Configuration Help Dialog.

simulator_help() {

  cmd=( yad \
    --center \
    --fixed \
    --align=left \
    --text-width=40 \
    --borders=20 \
    --window-icon="${__IMAGE}" \
    --title="${__TITLE}" \
    --borders=20 \
    --text="\
'Simulator Selection' and 'Terminal Window Configuration':

This dialog displays the currently selected Simulator along with the settings
for the Terminal Window that the Simulator will run in.

To change the Simulator that will be run, click on the ▼ symbol and select the
required one from the list displayed.

You can adjust the Width (columns), the Height (rows), the 'location' of the
Terminal Window and the Text Size. Use the -/+ buttons to decrease/increase the
displayed values OR highlight the value to be changed and enter a new value.

The 'location' of the Terminal Window is set by the X and Y Coordinate's. They
set the distance, in pixels, between the top-left corner of the Screen and the
top-left corner of the Terminal Window.

Text Size lets you adjust the size of the text within the Terminal Window.
Use a value of 1.0 to set the text to its Full size, 0.8 to reduce its size by
20% and 1.2 to increase its size by 20%.
 
Click the [Continue] button when you are ready to continue.

Click the [Cancel] button if you wish to terminate the program.

Click the [About] button to display the programs Version, Copyright and
License." \
    --button="Close"
    )

  "${cmd[@]}"

  }

export -f simulator_help

# ------------------------------------------------------------------------------
# Display the Scripts About Dialog.

about() {

  cmd=( yad \
    --about \
    --image="${__IMAGE}" \
    --pname="${__TITLE}" \
    --pversion="${__NAME} - ${__VERSION}" \
    --comments="" \
    --copyright="${__COPYRIGHT}" \
    --license="${__LICENSE}"
    )

  "${cmd[@]}"

  }

export -f about

# ------------------------------------------------------------------------------
# Display the Simulator Selection and Configuration Dialog.

simulator() {

  # Display dialog box with default values.
  
  yad_cmd=$( yad \
    --form \
    --center \
    --fixed \
    --align=left \
    --no-escape \
    --text-width=40 \
    --borders=20 \
    --window-icon="${__IMAGE}" \
    --title="${__TITLE}" \
    --text="Make your required changes and click [Continue] or [Cancel] to Exit:" \
    --focus-field=1 \
    --num-output \
    --field="\nSimulator Selection\n:LBL" "" \
    --field="    Simulator:CB" "${SIMULATORS}" \
    --field="\nTerminal Window Configuration\n:LBL" "" \
    --field="    Width!Set the width in columns.:NUM" "${SIM_WIDTH}" \
    --field="    Height!Set the height in rows.:NUM" "${SIM_HEIGHT}" \
    --field="    X Cordinate!Number of pixels between the left-hand side of the Screen and the left-hand side of the Window.:NUM" "${SIM_XCOORD}" \
    --field="    Y Cordinate!Number of pixels between the top of the Screen and the top of the Window.:NUM" "SIM_YCOORD" \
    --field="    Text Size!Set the size of the Text (1.0 = Full Size, 0.5 = 50% (Half Size), 2.0 = 200% (Double Size)):NUM" "${SIM_TEXT}!!0.1!1" \
    --field="\n:LBL" "" \
    --button="About!!Display the About Dialog.":"bash -c about" \
    --button="Help!!Display the Help Dialog.":"bash -c simulator_help" \
    --button="Cancel":1 \
    --button="Continue":0
    )

  status=$?

  if [[ ${status} -eq 1 ]]; then # Cancel button pressed.
    echo "** Program has been cancelled by the user."
    exit 0
    fi

  # Load returned values into global variables.
  
  #NOT_USED=`echo ${yad_cmd} | awk --field-separator='|' '{print $1}'`
  SIM=`echo ${yad_cmd} | awk --field-separator='|' '{print $2}'`
  #NOT_USED=`echo ${yad_cmd} | awk --field-separator='|' '{print $3}'`
  SIM_WIDTH=`echo ${yad_cmd} | awk --field-separator='|' '{print $4}'`
  SIM_HEIGHT=`echo ${yad_cmd} | awk --field-separator='|' '{print $5}'`
  SIM_XCOORD=`echo ${yad_cmd} | awk --field-separator='|' '{print $6}'`
  SIM_YCOORD=`echo ${yad_cmd} | awk --field-separator='|' '{print $7}'`
  SIM_TEXT=`echo ${yad_cmd} | awk --field-separator='|' '{print $8}'`

  }

export -f simulator

# = Mainline ===================================================================

# ------------------------------------------------------------------------------
# Check that INIFILE exists and is readable.

if [[ ! -r ${INIFILE} ]] ; then
  echo "** The INIFILE either does not exist OR it is not readable."
  echo "** Program Terminating **"
  exit 1
  fi

# ------------------------------------------------------------------------------
# Check that the required support programs exist. Terminate if they don't.

if ( ! command -v yad >/dev/null ) ; then
  echo "** Unable to find yad."
  echo "** Program Terminating **"
  exit 2
  fi

if ( ! command -v enscript >/dev/null ) ; then
  echo "** Unable to find enscript."
  echo "** Program Terminating **"
  exit 3
  fi

if ( ! command -v ps2pdf >/dev/null ) ; then
  echo "** Unable to find ps2pdf (part of GhostScript)."
  echo "** Program Terminating **"
  exit 4
  fi

# ------------------------------------------------------------------------------
# Display the Simulator Selection and Configuration Dialog.

# Get the number of available Simulators.

SIM_0=$(IniValue sim_0 [simulator])

# Set the Simulator Defaults.

SIMULATORS=$(IniValue "sim_1" [simulator])

for (( i=2; i<=$SIM_0; i++ )) ; do

  SIMULATORS+="!"
  SIMULATORS+=$(IniValue "sim_${i}" [simulator])

  done

# Set the Simulator Window Defaults.

SIM_WIDTH=$(IniValue columns [simulator_window])
SIM_HEIGHT=$(IniValue rows [simulator_window])
SIM_XCOORD=$(IniValue x_coordinate [simulator_window])
SIM_YCOORD=$(IniValue y_coordinate [simulator_window])
SIM_TEXT=$(IniValue text_size [simulator_window])

# Display the Simulator Dialog.

simulator

# Is the Convertor enabled for this Simulator?

CONV_ENABLED=$(IniValue "conv_${SIM}" [simulator])

# ------------------------------------------------------------------------------
# Display the LinePrinter to PDF Convertor Configuration Dialog.

if [[ ${CONV_ENABLED} == "YES" ]] ; then # Enabled.

  # Set the Convertor Defaults.

  HOST_IP=$(IniValue ip_address [convertor])
  HOST_PORT=$(IniValue tcp_port [convertor])
  PDF_MEDIA=$(IniValue output_media [convertor])
  BAR_LINES=$(IniValue lines_per_bar [convertor])
  BAR_COLOURS=$(IniValue bar_colours [convertor])
  PDF_DIRECTORY=$(IniValue directory [convertor])
  PDF_FONT=$(IniValue font_and_size [convertor])
  SYSTEM_ID=$(IniValue system_name [convertor])
  PRINTER_ID=$(IniValue printer_name [convertor])

  # Prefix this path with the users HOME directory.

  PDF_DIRECTORY="${HOME}${PDF_DIRECTORY}"

  # Set the Convertor Window Defaults.

  CONV_WIDTH=$(IniValue columns [convertor_window])
  CONV_HEIGHT=$(IniValue rows [convertor_window])
  CONV_XCOORD=$(IniValue x_coordinate [convertor_window])
  CONV_YCOORD=$(IniValue y_coordinate [convertor_window])
  CONV_TEXT=$(IniValue text_size [convertor_window])

  # Display the Convertor Dialog.

  convertor

  fi

# ------------------------------------------------------------------------------
# Terminate cleanly if the Host Port is already in use.

if [[ ${CONV_ENABLED} == "YES" ]] ; then # Convertor Enabled.

  TCP_PORT_IN_USE=$(lsof -nP -iTCP:${HOST_PORT})
  
  if [[ ${TCP_PORT_IN_USE} != "" ]] ; then # Host Port in use.
    echo "** The Host Port required by the Convertor is currently in use."
    echo "   Please wait a few minutes and try again."
    echo "** Program Terminating **"
    exit 5
    fi

  fi

# ------------------------------------------------------------------------------
# Switch to the correct directory and start the Simulator.

cd ${HOME}$(IniValue "dir_${SIM}" [simulator])

gnome-terminal \
  --title="$(IniValue "title_${SIM}" [simulator])" \
  --hide-menubar \
  --geometry=${SIM_WIDTH}x${SIM_HEIGHT}+${SIM_XCOORD}+${SIM_YCOORD} \
  --zoom=${SIM_TEXT} \
  -- hp3000 "$(IniValue "start_${SIM}" [simulator])"

status=$?

if [[ ${status} -eq 0 ]]; then
  echo "** The Simulator is now running."
else
  echo "** The Simulator has failed to start."
  echo "** Program Terminating **"
  exit 6
  fi

# ------------------------------------------------------------------------------
# Start the Convertor.

if [[ ${CONV_ENABLED} != "YES" ]] ; then # Exit if not enabled.
  exit 0
  fi

if [[ ${SYSTEM_ID} != "" ]] ; then
  SYSTEM_NAME="--system-id ${SYSTEM_ID}"
else
  SYSTEM_NAME=""
  fi

if [[ ${PRINTER_ID} != "" ]] ; then
  PRINTER_NAME="--name ${PRINTER_ID}"
else
  PRINTER_NAME=""
  fi

gnome-terminal \
  --title="HP3000 -- Line Printer ${PRINTER_NAME} to PDF" \
  --hide-menubar \
  --geometry=${CONV_WIDTH}x${CONV_HEIGHT}+${CONV_XCOORD}+${CONV_YCOORD} \
  --zoom=${CONV_TEXT} \
  -- elp2pdf.pl --lptype mpev --color ${BAR_COLOUR} --font ${PDF_FONT} --bar-height ${BAR_LINES} --ip ${HOST_IP} --port ${HOST_PORT} --path ${PDF_DIRECTORY} ${SYSTEM_NAME} ${PRINTER_NAME}

status=$?

if [[ ${status} -eq 0 ]]; then
  echo "** The Convertor is now running."
else
  echo "** The Convertor has failed to start."
  echo "** Program Terminating **"
  exit 7
  fi

# ------------------------------------------------------------------------------
# End of Program.

echo "End of Program"
